# Generated by Django 5.0.6 on 2024-07-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='rounds',
            field=models.IntegerField(choices=[(1, '1 Round')], default=1, help_text='Number of rounds'),
        ),
    ]
