# Generated by Django 5.0.6 on 2024-05-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='addresss',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='score_one',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='score_three',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='score_two',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
