# Generated by Django 5.0.6 on 2024-05-30 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0002_players_addresss_team_score_one_team_score_three_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='addresss',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='team',
            name='score_one',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='score_three',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='score_two',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tournament_images/'),
        ),
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.JSONField()),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bracket', to='tournament_app.tournament')),
            ],
        ),
    ]
