# Generated by Django 5.0.6 on 2024-10-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0002_tournament_timezone_alter_tournament_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
