# Generated by Django 5.0.6 on 2024-06-05 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0003_rename_addresss_players_address_alter_team_score_one_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('TA', 'Time Attack'), ('VAR', 'Variations in Set Rounds'), ('SRHS', 'Single Round Highest Score'), ('HTV', 'Hybrid of Time and Variations in Set Rounds'), ('HTSRHS', 'Hybrid of Time and Single Round Highest Score')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('time_limit', models.IntegerField(blank=True, null=True)),
                ('max_rounds', models.IntegerField(blank=True, null=True)),
                ('score_limit', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='game_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='tournament_app.gamemode'),
        ),
    ]
