# Generated by Django 5.0.6 on 2024-11-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0003_tournament_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='rounds',
            field=models.IntegerField(choices=[(1, '1 Round'), (2, '2 Rounds'), (3, '3 Rounds')], default=1, help_text='Number of rounds'),
        ),
    ]
