# Generated by Django 5.0.6 on 2024-07-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0004_team_score_edited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='score_edited',
            new_name='score_one_edited',
        ),
        migrations.RemoveField(
            model_name='team',
            name='time_total_score',
        ),
        migrations.RemoveField(
            model_name='team',
            name='total_score',
        ),
        migrations.AddField(
            model_name='team',
            name='score_three_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='score_two_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='time_score_one_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='time_score_three_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='time_score_two_edited',
            field=models.BooleanField(default=False),
        ),
    ]
