# Generated by Django 5.0.6 on 2024-07-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0005_rename_score_edited_team_score_one_edited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='time_total_score',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='total_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
