# Generated by Django 5.0.6 on 2024-07-05 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0006_team_time_total_score_team_total_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='score_one_edited',
        ),
        migrations.RemoveField(
            model_name='team',
            name='score_three_edited',
        ),
        migrations.RemoveField(
            model_name='team',
            name='score_two_edited',
        ),
        migrations.RemoveField(
            model_name='team',
            name='time_score_one_edited',
        ),
        migrations.RemoveField(
            model_name='team',
            name='time_score_three_edited',
        ),
        migrations.RemoveField(
            model_name='team',
            name='time_score_two_edited',
        ),
    ]
