# Generated by Django 5.0.6 on 2024-07-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0007_remove_team_score_one_edited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='score_one_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='score_three_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='score_two_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='time_score_one_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='time_score_three_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='time_score_two_edited',
            field=models.BooleanField(default=False),
        ),
    ]
