# Generated by Django 5.0.6 on 2024-06-07 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0007_bracket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hybridgamemode',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='scorebasedgamemode',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='timebasedgamemode',
            name='event_date',
        ),
        migrations.DeleteModel(
            name='Bracket',
        ),
    ]
