# Generated by Django 5.0.6 on 2024-06-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0010_remove_scorebasedgamemode_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='game_mode',
            field=models.CharField(choices=[('Time Attack', 'Time Attack: Best Time Wins'), ('Highest Score', 'Highest Score: Best Score Wins')], default='TimeAttack', max_length=20),
        ),
    ]
