# Generated by Django 5.0.6 on 2024-06-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0012_alter_tournament_game_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
