# Generated by Django 5.0.6 on 2024-06-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0013_tournament_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='guardian_name',
            new_name='coach',
        ),
        migrations.RemoveField(
            model_name='team',
            name='guardian_contact',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='game_mode',
            field=models.CharField(choices=[('TimeAttack', 'Time Attack: Complete the objective in the shortest time possible.'), ('HighestScore', 'Highest Score: Achieve the highest score to win.')], default='TimeAttack', max_length=20),
        ),
    ]
