# Generated by Django 5.0.6 on 2024-06-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0014_rename_guardian_name_team_coach_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='total_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
