# Generated by Django 5.0.6 on 2024-06-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0015_team_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='rules',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
