# Generated by Django 5.0.6 on 2024-06-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0017_remove_team_total_score_team_time_score_one_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='coach',
            new_name='guardian_contact',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='description',
        ),
        migrations.AddField(
            model_name='team',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='game_mode',
            field=models.CharField(choices=[('TimeAttack', 'Time Attack'), ('HighestScore', 'Highest Score')], default='HighestScore', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='rounds',
            field=models.IntegerField(choices=[(1, '1 Round'), (2, '2 Rounds'), (3, '3 Rounds')], default=1),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='rules',
            field=models.TextField(blank=True, null=True),
        ),
    ]
