# Generated by Django 5.0.6 on 2024-06-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0019_rename_guardian_name_team_coach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='time_score_one',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='time_score_three',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='time_score_two',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='time_total_score',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
