# Generated by Django 5.0.6 on 2024-06-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0020_alter_team_time_score_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='time_score_one',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='time_score_three',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='time_score_two',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='time_total_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
