# Generated by Django 5.0.6 on 2024-06-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0021_alter_team_time_score_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='video_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
