# Generated by Django 5.0.6 on 2024-06-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0023_alter_team_time_score_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='time_total_score',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
