# Generated by Django 5.0.6 on 2024-06-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0024_alter_team_time_total_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
