# Generated by Django 5.0.6 on 2024-06-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0025_alter_tournament_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[('RoboSports', 'Teams design 2 robots that compete with robots of another team.'), ('RoboMission', ' Build and program a robot that solves challenges on a field.'), ('FutureEngineers', 'Highest Score: Achieve the highest score to win.'), ('FutureInnovators', 'Develop a robot project that helps solve real world problems.')], default='RoboSports', max_length=20),
        ),
    ]
