# Generated by Django 5.0.6 on 2024-06-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0026_tournament_tournament_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[('RoboSports', 'RoboSports: Teams design 2 robots that compete with robots of another team.'), ('RoboMission', 'RoboMission: Build and program a robot that solves challenges on a field.'), ('FutureEngineers', 'FutureEngineers: Highest Score: Achieve the highest score to win.'), ('FutureInnovators', 'FutureInnovators: Develop a robot project that helps solve real world problems.')], default='RoboSports', max_length=20),
        ),
    ]
